{
 "title": "Foundation DB",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fdb_database_status", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_cpu_usage_cores) by (address, process_id)",
     "legendFormat": "{{address}} - {{process_id}}"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fdb_processes_disk_reads_total[5m])) by (address, process_id)",
     "legendFormat": "{{address}} - {{process_id}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fdb_processes_disk_writes_total[5m])) by (address, process_id)",
     "legendFormat": "{{address}} - {{process_id}}"
    }
   ]
  },
  {
   "title": "Network - Send",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_network_megabits_sent_per_second) by (address, process_id)",
     "legendFormat": "{{address}} - {{process_id}}"
    }
   ]
  },
  {
   "title": "Network - Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_network_megabits_received_per_second) by (address, process_id)",
     "legendFormat": "{{address}} - {{process_id}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_workload_operations_per_second) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_workload_transactions_per_second) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "FDB Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "FDB Storage - QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_storage_queries_per_second) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "FDB Storage - Mutations/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_storage_mutations_per_second) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Storage Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_storage_query_queue_max) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Storage Data Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_storage_data_lag_seconds) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Storage Queue - Disk used bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fdb_processes_queue_disk_used_bytes) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}