---
- hosts: 127.0.0.1
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.grafana
  vars:
    node_list: "{{ groups['as_private']|list + groups['loadgen_private']|list}}"
    prometheus_targets:
      node:
        - targets: "{{groups['as_private']|list|map('regex_replace', '$', ':9100')|flatten|list}}"
          labels:
            nodeType: db
        - targets: "{{groups['loadgen_private']|list|map('regex_replace', '$', ':9100')|flatten|list}}"
          labels:
            nodeType: loadgen
        - targets: "{{ [(groups['as_private'][0] + ':8080')] }}"
          labels:
            nodeType: fdbHeadNode
    grafana_datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "http://localhost:9090"
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: '1860'
        revision_id: '21'
        datasource: 'Prometheus'
    grafana_security:
      admin_user: admin
  tasks:
    - debug: var=node_list
